package com.m.downloaderlibrary.helper

const val OPEN_CONNECTION_ERROR = "OPEN_CONNECTION_ERROR"
const val CANCEL_DOWNLOAD = "CANCEL_DOWNLOAD"
const val INVALID_URL = "INVALID_URL"
const val EMPTY_RESPONSE = "EMPTY_RESPONSE"
const val DATA_NOT_FOUND_IN_CASH = "DATA_NOT_FOUND_IN_CASH"
